version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./dockeractividad:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production 